### ISSUE TITLE
app stops stream data to client /PC/ after go to background

### ISSUE THREAD

**Issue by KhenBai** [shiftinv/MotionSourceiOS#3]
Can you solve this issue. I searched some solution and found it. Here is a link https://stackoverflow.com/questions/14876359/socket-connection-killed-after-ios-app-goes-to-background. It won't solve problem properly, but it will help. I want to use it as gyro and pad screen simultaneously :>. Hope u solve that issue.

**Comment by shiftinv** [comment]
Closing in favor of #2
